In [1]:
import pandas as pd

In [2]:
df=pd.read_excel('Summer-Olympic-medals-1976-to-2008.xlsx')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15316 entries, 0 to 15315
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   City          15316 non-null  object
 1   Year          15316 non-null  int64
 2   Sport         15316 non-null  object
 3   Discipline    15316 non-null  object
 4   Event         15316 non-null  object
 5   Athlete       15316 non-null  object
 6   Gender        15316 non-null  object
 7   Country_Code  15316 non-null  object
 8   Country       15316 non-null  object
 9   Event_gender  15316 non-null  object
 10  Medal         15316 non-null  object
dtypes: int64(1), object(10)
memory usage: 1.3+ MB

In [5]:
df

,City,Year,Sport,Discipline,Event,Athlete,Gender,Country_Code,Country,Event_gender,Medal
0,Montreal,1976,Aquatics,Diving,3m springboard,"KÖHLER, Christa",Women,GDR,East Germany,W,Silver
1,Montreal,1976,Aquatics,Diving,3m springboard,"KOSENKOV, Aleksandr",Men,URS,Soviet Union,M,Bronze
2,Montreal,1976,Aquatics,Diving,3m springboard,"BOGGS, Philip George",Men,USA,United States,M,Gold
3,Montreal,1976,Aquatics,Diving,3m springboard,"CAGNOTTO, Giorgio Franco",Men,ITA,Italy,M,Silver
4,Montreal,1976,Aquatics,Diving,10m platform,"WILSON, Deborah Keplar",Women,USA,United States,W,Bronze
...,...,...,...,...,...,...,...,...,...,...,...
15311,Beijing,2008,Wrestling,Wrestling Gre-R,66 - 74kg,"GUENOT, Christophe",Men,FRA,France,M,Bronze
15312,Beijing,2008,Wrestling,Wrestling Gre-R,66 - 74kg,"KVIRKELIA, Manuchar",Men,GEO,Georgia,M,Gold
15313,Beijing,2008,Wrestling,Wrestling Gre-R,55 - 60kg,"RAHIMOV, Vitaliy",Men,AZE,Azerbaijan,M,Silver
15314,Beijing,2008,Wrestling,Wrestling Gre-R,60 - 66kg,"GUENOT, Steeve",Men,FRA,France,M,Gold
15315,Beijing,2008,Wrestling,Wrestling Gre-R,96 - 120kg,"LOPEZ, Mijain",Men,CUB,Cuba,M,Gold

## Questions to be Answered using the olympic dataset

### QUESTION 1:Top 10 Athletes with the most medals won

In [22]:
top_10_athletes=df.groupby(['Athlete','Country'])['Medal'].count().sort_values(ascending=False)
top_10_athletes.head(10)

Athlete                 Country
PHELPS, Michael         United States    16
TORRES, Dara            United States    12
ANDRIANOV, Nikolay      Soviet Union     12
THOMPSON, Jenny         United States    12
NEMOV, Alexei           Russia           12
BIONDI, Matthew         United States    11
COUGHLIN, Natalie       United States    11
LEWIS, Carl             United States    10
HALL, Gary Jr.          United States    10
VAN ALMSICK, Franziska  Germany          10
Name: Medal, dtype: int64

### Question 2: Which Country won the most gold medal?

In [24]:
country_gold_medals=df.query("Medal=='Gold'").groupby(['Country','Medal'])['Medal'].count().sort_values(ascending=False)
country_gold_medals

Country        Medal
United States  Gold     928
Soviet Union   Gold     439
East Germany   Gold     286
Germany        Gold     237
China          Gold     234
                       ...
Panama         Gold       1
Burundi        Gold       1
Suriname       Gold       1
Colombia       Gold       1
Tunisia        Gold       1
Name: Medal, Length: 87, dtype: int64

### Question 3: Which Country Won the Most Silver Medals?

In [13]:
country_silver_medals=df.query("Medal=='Silver'").groupby(['Country','Medal'])['Medal'].count().sort_values(ascending=False)
country_silver_medals

Country        Medal
United States  Silver    583
Soviet Union   Silver    285
Australia      Silver    270
China          Silver    252
Russia         Silver    206
                        ...
Kyrgyzstan     Silver      1
Senegal        Silver      1
Saudi Arabia   Silver      1
Puerto Rico*   Silver      1
Tajikistan     Silver      1
Name: Medal, Length: 106, dtype: int64

### Question 4:Which country won the most Bronze medals?

In [16]:
country_bronze_medals=df.query("Medal=='Bronze'").groupby(['Country','Medal'])['Medal'].count().sort_values(ascending=False)
country_bronze_medals

Country        Medal
United States  Bronze    481
Australia      Bronze    312
Soviet Union   Bronze    297
Germany        Bronze    278
Russia         Bronze    240
                        ...
Djibouti       Bronze      1
Cameroon       Bronze      1
Bermuda*       Bronze      1
Barbados       Bronze      1
Zimbabwe       Bronze      1
Name: Medal, Length: 108, dtype: int64

### Question 5: List down the total GOLD,SILVER,BRONZE won by Each Country

In [23]:
Total_medals=med.merge(bronze,on='Country')
Total_medals.rename(columns={'Medal_x':'Gold','Medal_y':'Silver','Medal':'Bronze'})

                    Gold  Silver  Bronze
Country
United States        928   583.0     481
Soviet Union         439   285.0     297
East Germany         286   190.0     150
Germany              237   176.0     278
China                234   252.0     193
...                  ...     ...     ...
Trinidad and Tobago    1     6.0       4
Syria                  1     1.0       1
Suriname               1     NaN       1
Colombia               1     2.0       5
Tunisia                1     NaN       1

[82 rows x 3 columns]

In [4]:
gold=df.query("Medal=='Gold'").groupby(['Country'])['Medal'].count().sort_values(ascending=False)
gold

Country
United States    928
Soviet Union     439
East Germany     286
Germany          237
China            234
                ...
Panama             1
Burundi            1
Suriname           1
Colombia           1
Tunisia            1
Name: Medal, Length: 87, dtype: int64

In [15]:
silver=df.query("Medal=='Silver'").groupby(['Country'])['Medal'].count().sort_values(ascending=False)
silver

Country
United States    583
Soviet Union     285
Australia        270
China            252
Russia           206
                ...
Kyrgyzstan         1
Senegal            1
Saudi Arabia       1
Puerto Rico*       1
Tajikistan         1
Name: Medal, Length: 106, dtype: int64

In [16]:
bronze=df.query("Medal=='Bronze'").groupby(['Country'])['Medal'].count().sort_values(ascending=False)
bronze

Country
United States    481
Australia        312
Soviet Union     297
Germany          278
Russia           240
                ...
Djibouti           1
Cameroon           1
Bermuda*           1
Barbados           1
Zimbabwe           1
Name: Medal, Length: 108, dtype: int64

### Question 6: List down total number of sports played in each Olympic

In [35]:
total_sport=df.groupby(['Year'])['Sport'].nunique()
total_sport

Year
1976    21
1980    21
1984    21
1988    23
1992    25
1996    26
2000    28
2004    28
2008    28
Name: Sport, dtype: int64

### Questin 7: All THE OLYMPIC GAMES HELD SO FAR

In [39]:
df['Year'].nunique()

9

### Question 9: Total Number of Nations That Participated in Each Olympic Game

In [44]:
total_nations=df.groupby(['Year','City'])['Country'].nunique()
total_nations

Year  City
1976  Montreal       41
1980  Moscow         36
1984  Los Angeles    47
1988  Seoul          52
1992  Barcelona      64
1996  Atlanta        79
2000  Sydney         80
2004  Athens         74
2008  Beijing        86
Name: Country, dtype: int64

### Question 10: Sport in which India Has the most Medals

In [49]:
india=df.query("Country=='India'").groupby(['Sport','Event'])['Medal'].count()
india

Sport          Event
Boxing         69 - 75 kg                    1
Hockey         hockey                       16
Shooting       10m air rifle (60 shots)      1
               double trap (150 targets)     1
Tennis         singles                       1
Weightlifting  69kg                          1
Wrestling      60 - 66kg                     1
Name: Medal, dtype: int64